name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/mkdocs.yaml'
      - 'contributing/**'
  workflow_dispatch:

permissions:
  contents: write
  deployments: write
  pages: write

jobs:
  build:
    name: Publish Contributor GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Publish
        uses: mhausenblas/mkdocs-deploy-gh-pages@d77dd03172e96abbcdb081d8c948224762033653 # 1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yml
